# Generated by Django 4.2.25 on 2025-10-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
